// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practice.DAO;

namespace Practice.Migrations
{
    [DbContext(typeof(BandDbContext))]
    [Migration("20200902193025_AddDbSets")]
    partial class AddDbSets
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("Practice.Models.AlbumModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BandModelid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("albumDesc")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasMaxLength(1000);

                    b.Property<int>("albumRating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("albumTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("BandModelid");

                    b.ToTable("albums");
                });

            modelBuilder.Entity("Practice.Models.BandModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("bandName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("musicGenre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("bands");
                });

            modelBuilder.Entity("Practice.Models.AlbumModel", b =>
                {
                    b.HasOne("Practice.Models.BandModel", null)
                        .WithMany("albums")
                        .HasForeignKey("BandModelid");
                });
#pragma warning restore 612, 618
        }
    }
}
